"""Generate crawlable lesson pages and a sitemap from the shared help source.

No dependencies or network access are needed. Run --check before deployment to
detect stale pages; edit docs/help/topics.json rather than generated lesson HTML.
"""
import argparse
import html
import json
from pathlib import Path
import textwrap

from build_help import outputs as validate_topics, render_html

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/help/topics.json'
SITE = ROOT / 'website-preview/dist'
BASE = 'https://velocityeu.github.io/NetTools/'
CORPORATE = 'https://www.velocity-eu.com/'
GENERATED = '<!-- Generated by scripts/build_seo.py from docs/help/topics.json. -->'
INDEX_TITLE = 'Subnetting and network field guide'
INDEX_DESCRIPTION = ('Learn IPv4 and IPv6 subnetting, VLSM, exact CIDR aggregation and network '
                     'diagnostics with worked lessons and practical explanations by VEU.')

# Page-specific layout; the shared site stylesheet supplies the brand and lesson
# components. Asset URLs are relative so the same pages work in local previews.
PAGE_STYLE = """
.seo-header{border-bottom:1px solid var(--line)}
.seo-brand{display:flex;gap:16px;align-items:center;text-decoration:none;color:var(--blue);font-size:1.2rem;font-weight:650}
.seo-logo{display:flex;background:#152333;padding:13px 17px;border-radius:4px;flex-shrink:0}
.seo-logo img{display:block;width:150px;height:auto}
.breadcrumbs{padding-block:22px;font-size:.9rem}
.breadcrumbs ol{display:flex;flex-wrap:wrap;gap:8px;list-style:none;padding:0;margin:0}
.breadcrumbs li+li:before{content:' / ';color:var(--muted);margin-right:8px}
.seo-main .help-section{padding-block:30px 60px}.seo-main h1{font-size:clamp(2rem,4vw,3rem);line-height:1.15;letter-spacing:-.035em}
.seo-main .help-article h2{font-size:1.2rem;letter-spacing:-.015em;margin:28px 0 12px;line-height:1.3}
.seo-main .lesson-step h2{margin-top:0}.seo-main .help-nav nav{display:block;max-height:none;overflow:visible}
.seo-main .topic{font-size:.88rem;text-decoration:none}.seo-main .topic[aria-current=page]{background:#dceaf8;color:var(--blue);font-weight:650}
.seo-main .article-pager{display:flex;justify-content:space-between;gap:24px;border-top:1px solid var(--line);margin-top:32px;padding-top:22px}
.seo-main .article-pager a{max-width:48%;font-size:.9rem}.lesson-author{font-size:.9rem;color:var(--muted)}
.seo-index{max-width:980px;padding-bottom:45px}.seo-index ol{padding-left:24px}.seo-index li{padding:18px 0;border-bottom:1px solid var(--line)}
.seo-index li a{font-size:1.2rem;font-weight:600}.seo-index li p{margin:8px 0 0;color:var(--muted)}
@media(max-width:600px){.seo-brand{font-size:1rem;gap:10px}.seo-logo{padding:10px}.seo-logo img{width:110px}}
@media print{.breadcrumbs,.seo-header{display:none}.seo-main .help-section{padding:0}.seo-main h1{font-size:24pt}}
""".strip()


def plain_text(node):
    if isinstance(node, str):
        return node
    return ''.join(plain_text(child) for child in node['children'])


def description(topic):
    paragraphs = [plain_text(block) for block in topic['blocks']
                  if isinstance(block, dict) and block['type'] == 'paragraph'
                  and block.get('variant') not in {'lesson-meta', 'reference'}]
    explanation = next((text for text in paragraphs if text.strip()),
                       ''.join(plain_text(block) for block in topic['blocks']))
    return textwrap.shorten(f'{topic["title"]}. {explanation}', width=165, placeholder='…')


def topic_url(topic):
    return BASE + 'help/' + topic['id'] + '/'


def graph(title, summary, canonical, crumbs, topic=None, topics=()):
    organization_id, website_id = BASE + '#organization', BASE + '#website'
    webpage_id, breadcrumb_id = canonical + '#webpage', canonical + '#breadcrumbs'
    organization = {'@type': 'Organization', '@id': organization_id, 'name': 'VEU',
                    'url': CORPORATE, 'logo': BASE + 'velocity-corporate-logo.png'}
    website = {'@type': 'WebSite', '@id': website_id, 'url': BASE,
               'name': 'Velocity NetTools', 'inLanguage': 'en',
               'publisher': {'@id': organization_id}}
    webpage = {'@type': 'WebPage' if topic else 'CollectionPage', '@id': webpage_id,
               'url': canonical, 'name': title, 'description': summary,
               'inLanguage': 'en', 'isPartOf': {'@id': website_id},
               'publisher': {'@id': organization_id}, 'breadcrumb': {'@id': breadcrumb_id}}
    breadcrumbs = {'@type': 'BreadcrumbList', '@id': breadcrumb_id,
                   'itemListElement': [
                       {'@type': 'ListItem', 'position': index, 'name': name, 'item': url}
                       for index, (name, url) in enumerate(crumbs, 1)]}
    nodes = [organization, website, webpage, breadcrumbs]
    if topic:
        lesson_id = canonical + '#lesson'
        webpage['mainEntity'] = {'@id': lesson_id}
        nodes.append({'@type': ['TechArticle', 'LearningResource'], '@id': lesson_id,
                      'url': canonical, 'headline': title, 'name': title,
                      'description': summary, 'inLanguage': 'en',
                      'author': {'@id': organization_id}, 'publisher': {'@id': organization_id},
                      'mainEntityOfPage': {'@id': webpage_id}, 'isPartOf': {'@id': website_id},
                      'learningResourceType': 'Lesson', 'teaches': title,
                      'isAccessibleForFree': True})
    else:
        webpage['hasPart'] = [{'@id': topic_url(item) + '#lesson'} for item in topics]
    return {'@context': 'https://schema.org', '@graph': nodes}


def shell(title, summary, canonical, body, crumbs, depth, structured):
    asset_root = '../' * depth
    esc = html.escape
    breadcrumb_items = []
    for index, (name, url) in enumerate(crumbs):
        if index == len(crumbs) - 1:
            breadcrumb_items.append(f'<li aria-current="page">{esc(name)}</li>')
        else:
            relative = asset_root + url.removeprefix(BASE)
            breadcrumb_items.append(f'<li><a href="{esc(relative, quote=True)}">{esc(name)}</a></li>')
    schema = json.dumps(structured, ensure_ascii=False, indent=2).replace('<', '\\u003c')
    return f'''<!doctype html>
{GENERATED}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} | Velocity NetTools by VEU</title>
<meta name="description" content="{esc(summary, quote=True)}">
<meta name="author" content="VEU">
<meta name="publisher" content="VEU">
<link rel="canonical" href="{canonical}">
<meta property="og:type" content="{('article' if depth == 2 else 'website')}">
<meta property="og:title" content="{esc(title, quote=True)} | Velocity NetTools">
<meta property="og:description" content="{esc(summary, quote=True)}">
<meta property="og:url" content="{canonical}">
<meta property="og:site_name" content="Velocity NetTools">
<link rel="icon" type="image/png" href="{asset_root}velocity-corporate-favicon.png">
<link rel="stylesheet" href="{asset_root}style.css">
<style>{PAGE_STYLE}</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<a href="#main" class="skip">Skip to lesson content</a>
<header class="seo-header"><div class="site-header wrap">
<a class="seo-brand" href="{asset_root}"><span class="seo-logo"><img src="{asset_root}velocity-corporate-logo.png" alt="VEU corporate logo" width="1432" height="307"></span><span>Velocity NetTools</span></a>
<nav aria-label="Main navigation"><a href="{asset_root}help/">Field guide</a><a href="{asset_root}#download">Downloads</a><a href="{CORPORATE}">VEU</a></nav>
</div></header>
<nav class="breadcrumbs wrap" aria-label="Breadcrumb"><ol>{''.join(breadcrumb_items)}</ol></nav>
<main id="main" class="seo-main">{body}</main>
<footer class="wrap"><p><strong>Velocity NetTools</strong><br>Written and published by VEU.</p><div><a href="{CORPORATE}">VEU corporate website</a><p><a href="{asset_root}help/">All field guide lessons</a> · <a href="{asset_root}license.txt">MIT licence</a></p></div></footer>
</body>
</html>
'''


def lesson_page(topic, topics, index):
    esc, canonical = html.escape, topic_url(topic)
    crumbs = [('Velocity NetTools', BASE), ('Field guide', BASE + 'help/'),
              (topic['title'], canonical)]
    nav = ''.join(f'<a class="topic" href="../{item["id"]}/"'
                  + (' aria-current="page"' if item['id'] == topic['id'] else '')
                  + f'>{esc(item["title"])}</a>' for item in topics)
    # The shared renderer emits h4 for the interactive article widget. These
    # standalone lessons use h2 directly below their single page h1.
    content = ''.join(render_html(block) for block in topic['blocks'])
    content = content.replace('<h4>', '<h2>').replace('</h4>', '</h2>')
    pager = []
    if index:
        previous = topics[index - 1]
        pager.append(f'<a rel="prev" href="../{previous["id"]}/">Previous: {esc(previous["title"])}</a>')
    if index + 1 < len(topics):
        following = topics[index + 1]
        pager.append(f'<a rel="next" href="../{following["id"]}/">Next: {esc(following["title"])}</a>')
    body = f'''<section class="help-section"><div class="wrap help-workspace">
<aside class="help-nav"><p><strong>Field guide lessons</strong></p><nav aria-label="All lessons">{nav}</nav></aside>
<article class="help-article" aria-labelledby="lesson-title"><h1 id="lesson-title">{esc(topic['title'])}</h1>
<p class="lesson-author">Written and published by <a href="{CORPORATE}" rel="author">VEU</a>.</p>
{content}
<nav class="article-pager" aria-label="Previous and next lessons">{''.join(pager)}</nav>
</article></div></section>'''
    summary = description(topic)
    return shell(topic['title'], summary, canonical, body, crumbs, 2,
                 graph(topic['title'], summary, canonical, crumbs, topic=topic))


def outputs(data, output_dir=SITE):
    validate_topics(data)  # Reuse the shared topic/schema/HTML safety validation.
    topics = data['topics']
    if not topics:
        raise ValueError('The field guide requires at least one lesson')
    output_dir = Path(output_dir)
    result = {output_dir / 'help' / topic['id'] / 'index.html': lesson_page(topic, topics, index)
              for index, topic in enumerate(topics)}
    items = ''.join(f'<li><a href="{topic["id"]}/">{html.escape(topic["title"])}</a>'
                    f'<p>{html.escape(description(topic))}</p></li>' for topic in topics)
    body = f'''<section class="wrap seo-index"><h1>{INDEX_TITLE}</h1>
<p>{INDEX_DESCRIPTION}</p><p class="lesson-author">Written and published by <a href="{CORPORATE}" rel="author">VEU</a>.</p>
<p>Choose one of {len(topics)} lessons. Each page includes the complete explanation and links to the next lesson.</p>
<nav aria-label="All field guide lessons"><ol>{items}</ol></nav></section>'''
    crumbs = [('Velocity NetTools', BASE), ('Field guide', BASE + 'help/')]
    result[output_dir / 'help/index.html'] = shell(
        INDEX_TITLE, INDEX_DESCRIPTION, BASE + 'help/', body, crumbs, 1,
        graph(INDEX_TITLE, INDEX_DESCRIPTION, BASE + 'help/', crumbs, topics=topics))
    locations = [BASE, BASE + 'help/'] + [topic_url(topic) for topic in topics]
    result[output_dir / 'sitemap.xml'] = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + ''.join(f'  <url><loc>{html.escape(url)}</loc></url>\n' for url in locations)
        + '</urlset>\n')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--source', type=Path, default=SOURCE)
    parser.add_argument('--output', type=Path, default=SITE)
    args = parser.parse_args()
    try:
        result = outputs(json.loads(args.source.read_text(encoding='utf-8')), args.output.resolve())
        obsolete = [path for path in (args.output / 'help').glob('*/index.html')
                    if path.resolve() not in result and GENERATED in path.read_text(encoding='utf-8')]
        stale = [str(path.relative_to(args.output.resolve())) for path, content in result.items()
                 if not path.exists() or path.read_text(encoding='utf-8') != content]
        if args.check:
            if stale or obsolete:
                raise ValueError('Generated search pages are stale: ' + ', '.join(stale + [str(path) for path in obsolete]))
        else:
            for path, content in result.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding='utf-8')
            # Only remove obsolete files bearing this generator's ownership marker.
            for path in obsolete:
                path.unlink()
        print('Search pages and sitemap match the shared help source.' if args.check
              else f'Generated {len(result) - 2} lesson pages, the field guide index and sitemap.')
    except (OSError, ValueError, KeyError, TypeError) as error:
        raise SystemExit(f'Search-page generation failed: {error}') from error


if __name__ == '__main__':
    main()
