"""Package the app shell after build_pwa.py; generated files are deterministic."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE_FILES = ('index.html', 'style.css', 'app.mjs', 'engine-client.mjs', 'worker.mjs',
              'engine.mjs', 'engine.wasm', 'plans.mjs', 'public-ip.mjs', 'notices.txt')
HELP_IDS = ('subnetting-by-hand-five-steps', 'bits-bytes-and-powers-of-two',
            'from-prefix-to-subnet-mask', 'cross-an-octet-boundary-20',
            'choose-a-prefix-for-host-capacity', 'split-a-network-into-equal-parts',
            'glossary-and-common-mistakes', 'understand-an-ipv4-subnet', 'plan-with-vlsm',
            'use-31-and-32-correctly', 'understand-ipv6-prefixes',
            'ipv6-127-and-128-in-practice', 'the-0-boundary-and-exact-counts',
            'input-errors', 'pinned-vlsm', 'web-app-getting-started',
            'web-app-calculations-and-plans', 'web-app-offline-updates-and-privacy')

SW_TEMPLATE = r'''/* Generated by scripts/package_pwa.py. Scope: this app directory only. */
const VERSION = __VERSION__;
const FILES = __FILES__;
const HASHES = __HASHES__;
const BASE = self.registration.scope;
const PREFIX = 'velocity-nettools-app:' + BASE + ':';
const CACHE = PREFIX + VERSION;
const URLS = FILES.map(file => new URL(file, BASE).href);
async function complete(cache) {
  return (await Promise.all(URLS.map(url => cache.match(url)))).every(Boolean);
}
async function verifiedShell() {
  return await Promise.all(URLS.map(async (url, index) => {
    const response = await fetch(new Request(url, {cache: 'reload'}));
    if (!response.ok) throw new Error('Unable to fetch the complete app shell');
    const bytes = await response.clone().arrayBuffer();
    const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)))
      .map(value => value.toString(16).padStart(2, '0')).join('');
    if (hash !== HASHES[FILES[index]]) throw new Error('App version integrity mismatch');
    return [url, response];
  }));
}
async function storeShell(cache, entries) {
  // Every response is validated before the first write. A quota failure can only
  // leave missing entries, never insert bytes from a different app version.
  for (const [url, response] of entries) await cache.put(url, response);
}
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE);
      await storeShell(cache, await verifiedShell());
      if (!await complete(cache)) throw new Error('Incomplete offline shell');
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
    // Updates wait for the user's explicit ACTIVATE message.
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    if (!await complete(cache)) return;
    // Old-registration windows may still need any older shell after an explicit reset.
    if (!(await appClients()).length) {
      await Promise.all((await caches.keys()).filter(key => key.startsWith(PREFIX) && key !== CACHE)
        .slice(0, -1).map(key => caches.delete(key)));
    }
    // Do not claim unrelated/old-registration windows after an explicit reset.
    // Initial installation controls the next navigation; normal updates switch existing clients.
  })());
});
let repair = null;
function repairShell() {
    if (!repair) repair = (async () => {
      try {
        const entries = await verifiedShell();
        const cache = await caches.open(CACHE);
        await storeShell(cache, entries);
        return {ready: await complete(cache), version: VERSION};
      } catch (_) {
        return {ready: false, error: 'Repair could not verify this app version. Check for updates; if needed, save your work, close all app tabs and reopen online.'};
      }
    })().finally(() => { repair = null; });
    return repair;
}
let activation = null;
let ballot = null;
async function appClients() {
  const base = new URL(BASE);
  return (await self.clients.matchAll({type: 'window', includeUncontrolled: true})).filter(client => {
    const url = new URL(client.url);
    return url.origin === base.origin && url.pathname.startsWith(base.pathname);
  });
}
async function requestActivation() {
  let clients = [];
  let approved = false;
  try {
    if (!await complete(await caches.open(CACHE))) return false;
    clients = await appClients();
    const nonce = crypto.randomUUID();
    const ids = new Set(clients.map(client => client.id));
    approved = await new Promise(resolve => {
      const timeout = setTimeout(() => finish(false), 3000);
      function finish(ready) { clearTimeout(timeout); resolve(ready); }
      ballot = {nonce, ids, votes: new Set(), finish};
      if (!ids.size) finish(true);
      for (const client of clients) client.postMessage({type: 'UPDATE_QUERY', nonce});
    });
    ballot = null;
    // A newly opened window has not consented. Closed windows are harmless.
    if (approved && (await appClients()).some(client => !ids.has(client.id))) approved = false;
    if (approved && !await complete(await caches.open(CACHE))) approved = false;
    if (approved) await self.skipWaiting();
    return approved;
  } catch (_) { approved = false; return false; }
  finally {
    ballot = null;
    if (!approved) for (const client of clients) {
      try { client.postMessage({type: 'UPDATE_BLOCKED'}); } catch (_) {}
    }
  }
}
self.addEventListener('message', event => {
  if (event.data?.type === 'REPAIR' && event.ports?.[0]) {
    const task = repairShell();
    event.waitUntil(task.then(result => event.ports[0].postMessage(result)));
  }
  if (event.data?.type === 'UPDATE_VOTE' && ballot && event.data.nonce === ballot.nonce
      && ballot.ids.has(event.source?.id)) {
    if (event.data.ready !== true) ballot.finish(false);
    else {
      ballot.votes.add(event.source.id);
      if (ballot.votes.size === ballot.ids.size) ballot.finish(true);
    }
  }
  if (event.data?.type === 'ACTIVATE') {
    if (!activation) activation = requestActivation().finally(() => { activation = null; });
    event.waitUntil(activation.then(approved => {
      if (!approved) event.source?.postMessage({type: 'UPDATE_BLOCKED'});
    }));
  }
  if (event.data?.type === 'STATUS' && event.ports?.[0]) {
    event.waitUntil((async () => {
      let ready = false;
      try { ready = await complete(await caches.open(CACHE)); } catch (_) {}
      event.ports[0].postMessage({ready, version: VERSION});
    })());
  }
});
function recoveryPage() {
  const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recover Velocity NetTools</title>
<style>body{font:18px system-ui;max-width:38rem;margin:3rem auto;padding:1rem;line-height:1.6}button,a{font:inherit;min-height:44px;margin:.5rem .5rem .5rem 0}button{padding:.5rem 1rem}body{color-scheme:light dark}</style>
<h1>Offline app needs repair</h1><p>The saved app shell is incomplete. A verified copy of this version could not be downloaded. Connect to the internet and retry.</p>
<button id="retry">Retry online</button><button id="reset">Reset installation</button><p id="status" role="status"></p>
<p>If a newer version is available, Reset installation opens a fresh online copy. It preserves saved plans and cached data. Other open tabs keep their existing app; save any work there before closing them.</p><a id="learn">Open the learning centre</a>
<script>
const base = ${JSON.stringify(BASE)};
const status = document.getElementById('status');
document.getElementById('learn').href = new URL('../',base).href;
navigator.serviceWorker.addEventListener('message', event => {
  if(event.data?.type === 'UPDATE_QUERY') event.source.postMessage({type:'UPDATE_VOTE',nonce:event.data.nonce,ready:true});
});
navigator.serviceWorker.addEventListener('controllerchange',()=>location.replace(base));
document.getElementById('retry').onclick = async () => {
  status.textContent = 'Checking the complete app shell...';
  try {
    const registration = await navigator.serviceWorker.getRegistration(base);
    const worker = navigator.serviceWorker.controller || registration?.active;
    if(!worker) {location.replace(base);return;}
    const result = await new Promise((resolve,reject)=>{
      const channel = new MessageChannel();
      const timer = setTimeout(()=>{channel.port1.close();reject(new Error('Repair timed out. Try again when online.'));},20000);
      channel.port1.onmessage = event => {clearTimeout(timer);channel.port1.close();resolve(event.data);};
      worker.postMessage({type:'REPAIR'},[channel.port2]);
    });
    if(result.ready) location.replace(base);
    else status.textContent = 'This version could not be repaired. Try Reset installation while online.';
  } catch(error) {status.textContent = error.message;}
};
document.getElementById('reset').onclick = async () => {
  try {
    const registration = await navigator.serviceWorker.getRegistration(base);
    if(registration && !await registration.unregister()) throw new Error('Reset failed. Please retry.');
    location.replace(base);
  } catch(error) {status.textContent = error.message;}
};
</script></html>`;
  return new Response(html, {status:503,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  const base = new URL(BASE);
  if (request.method !== 'GET' || url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const key = request.mode === 'navigate' ? new URL('index.html', BASE).href : url.href;
  if (!URLS.includes(key)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (request.mode === 'navigate') {
      if (await complete(cache) || (await repairShell()).ready) return await cache.match(key);
      return recoveryPage();
    }
    const cached = await cache.match(key);
    if (cached) return cached;
    return new Response('Offline cache incomplete. Use Learn > Repair offline cache. If the app cannot load, close all app tabs and reopen online.',
      {status: 503, headers: {'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store'}});
  })());
});
'''


def write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def build(out, topics, favicon):
    from PIL import Image
    out = Path(out)
    for name in CORE_FILES:
        if not (out / name).is_file():
            raise FileNotFoundError(f'Missing app shell asset: {name}; build the app first')
    canonical = json.loads(Path(topics).read_text(encoding='utf-8'))
    selected = [topic for topic in canonical['topics'] if topic['id'] in HELP_IDS]
    if {topic['id'] for topic in selected} != set(HELP_IDS):
        raise ValueError('Canonical PWA help topics are missing')
    write_json(out / 'help.json', {'schemaVersion': canonical['schemaVersion'], 'topics': selected})
    (out / 'icons').mkdir(exist_ok=True)
    icon_files = ('icons/icon-192.png', 'icons/icon-512.png', 'icons/apple-touch-icon.png')
    with Image.open(favicon) as mark:
        # Resize the exact corporate asset; do not redraw or replace its artwork.
        for size, name in zip((192, 512, 180), icon_files):
            mark.convert('RGBA').resize((size, size), Image.Resampling.LANCZOS).save(out / name)
    write_json(out / 'manifest.webmanifest', {
        'id': './', 'name': 'Velocity NetTools', 'short_name': 'NetTools',
        'description': 'IPv4 and IPv6 subnet calculation and planning by VEU.',
        'lang': 'en', 'start_url': './', 'scope': './', 'display': 'standalone',
        'background_color': '#f2f2f7', 'theme_color': '#f2f2f7',
        'icons': [{'src': name, 'sizes': f'{size}x{size}', 'type': 'image/png', 'purpose': 'any'}
                  for size, name in zip((192, 512), icon_files)]})
    files = CORE_FILES + ('help.json', 'manifest.webmanifest') + icon_files
    digest = hashlib.sha256(SW_TEMPLATE.encode())
    for name in files:
        digest.update(name.encode() + b'\0' + hashlib.sha256((out / name).read_bytes()).digest())
    version = digest.hexdigest()[:24]
    hashes = {name: hashlib.sha256((out / name).read_bytes()).hexdigest() for name in files}
    worker = SW_TEMPLATE.replace('__VERSION__', json.dumps(version)).replace('__FILES__', json.dumps(files)).replace('__HASHES__', json.dumps(hashes))
    (out / 'sw.js').write_text(worker, encoding='utf-8', newline='\n')
    return version


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'website-preview/dist/app')
    args = parser.parse_args()
    version = build(args.output, ROOT / 'docs/help/topics.json', ROOT / 'website-preview/dist/velocity-corporate-favicon.png')
    print(f'Packaged offline app version {version}')


if __name__ == '__main__':
    main()
